#!/bin/bash
#SBATCH --job-name=k2_to_tax_h1
#SBATCH --partition=cpu1
#SBATCH --output=/home/jtay0094/k2_to_tax_h1_%j.out
#SBATCH --error=/home/jtay0094/k2_to_tax_h1_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G

set -eo pipefail
echo "START: $(date)"

source /home/jtay0094/miniconda3/etc/profile.d/conda.sh
conda activate qiime2-moshpit-2025.7

BASE="/home/jtay0094/MAGs/healthy1/taxonomy/kraken2_pluspf_derep098"

REPORTS="$BASE/kraken2-reports-mags.qza"
OUTPUTS="$BASE/kraken2-hits-mags.qza"

TAX_OUT="$BASE/mags-taxonomy.qza"

[[ -f "$REPORTS" ]] || { echo "ERROR: Missing $REPORTS" >&2; exit 1; }
[[ -f "$OUTPUTS" ]] || { echo "ERROR: Missing $OUTPUTS" >&2; exit 1; }

mosh annotate kraken2-to-mag-features \
  --i-reports "$REPORTS" \
  --i-outputs "$OUTPUTS" \
  --o-taxonomy "$TAX_OUT" \
  --verbose

echo "END: $(date)"
echo "Taxonomy saved to: $TAX_OUT"
